/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import domínio.Bebida;
import domínio.Comida;
import domínio.Item;
import domínio.Pessoa;
import java.util.Iterator;
import java.util.LinkedList;
import javax.swing.DefaultListModel;
/**
 *
 * @author User
 */

public class Principal extends javax.swing.JFrame {

    private static LinkedList listaPessoa = new LinkedList();
    private static LinkedList listaItem = new LinkedList();

    private DefaultListModel modeloPessoas = new DefaultListModel();
    private DefaultListModel modeloItens = new DefaultListModel();

    /**
     * Creates new form Principal
     */
    
    int contC = 0;
    float custoBebidas = 0, custoComidas = 0, custoTotal = 0, custoConvidado = 0;
    
    public Principal() {
        initComponents();
        
    }
    
    public static void setPessoa(Pessoa pes) {
        Principal.listaPessoa.add(pes);
    }
    
    static void setItem(Item it) {
       Principal.listaItem.add(it);
    }
    
    public static void atualizarjComboBoxPessoas(){
        jComboBoxPessoas.removeAllItems();
        
    Iterator i = listaPessoa.iterator();
    while (i.hasNext()){
        String pes = i.next().toString();
        System.out.println(pes);
        jComboBoxPessoas.addItem(pes.toString());
    }
    jComboBoxPessoas.setSelectedIndex(-1);
    }
    
    public static void atualizarjComboBoxItens(){
        jComboBoxItens.removeAllItems();
        for (int x = 0; x < listaItem.size(); x++) {
            Item it = (Item) listaItem.get(x);
            jComboBoxItens.addItem(it.toString());
        }
        jComboBoxItens.setSelectedIndex(-1);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxPessoas = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxItens = new javax.swing.JComboBox<>();
        jButtonLimparPessoas = new javax.swing.JButton();
        jButtonAdicionarPessoas = new javax.swing.JButton();
        jButtonLimparItens = new javax.swing.JButton();
        jButtonAdicionarItens = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListConvidados = new javax.swing.JList<>();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListItens = new javax.swing.JList<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabelNumConvidados = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabelCustoComidas = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabelCustoBebidas = new javax.swing.JLabel();
        jLabelCustoTotal = new javax.swing.JLabel();
        jLabelCustoConvidado = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuCadPessoa = new javax.swing.JMenu();
        jMenuCadItens = new javax.swing.JMenu();
        jMenuSobre = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Festa Topzera");

        jPanel1.setBackground(new java.awt.Color(248, 236, 230));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Pessoas");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Itens");

        jButtonLimparPessoas.setText("Limpar");
        jButtonLimparPessoas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparPessoasActionPerformed(evt);
            }
        });

        jButtonAdicionarPessoas.setText("Adicionar Convidado");
        jButtonAdicionarPessoas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdicionarPessoasActionPerformed(evt);
            }
        });

        jButtonLimparItens.setText("Limpar");
        jButtonLimparItens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparItensActionPerformed(evt);
            }
        });

        jButtonAdicionarItens.setText("Adicionar Item");
        jButtonAdicionarItens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdicionarItensActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Lista de Convidados");

        jListConvidados.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jScrollPane1.setViewportView(jListConvidados);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Lista de Itens");

        jListItens.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jScrollPane2.setViewportView(jListItens);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("RESUMO DA FESTA:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Número de Convidados:");

        jLabelNumConvidados.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelNumConvidados.setForeground(new java.awt.Color(255, 51, 51));
        jLabelNumConvidados.setText("XX");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Custo das Comidas (R$): ");

        jLabelCustoComidas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelCustoComidas.setForeground(new java.awt.Color(255, 51, 51));
        jLabelCustoComidas.setText("XX");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Custo das Bebidas (R$):");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Custo Total (R$):");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Custo por Convidado (R$):");

        jLabelCustoBebidas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelCustoBebidas.setForeground(new java.awt.Color(255, 51, 51));
        jLabelCustoBebidas.setText("XX");

        jLabelCustoTotal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelCustoTotal.setForeground(new java.awt.Color(255, 51, 51));
        jLabelCustoTotal.setText("XX");

        jLabelCustoConvidado.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelCustoConvidado.setForeground(new java.awt.Color(255, 51, 51));
        jLabelCustoConvidado.setText("XX");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabelCustoBebidas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabelCustoComidas, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabelNumConvidados, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel5))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelCustoTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelCustoConvidado, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(154, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel5)
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabelNumConvidados))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabelCustoComidas))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabelCustoBebidas))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabelCustoTotal))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabelCustoConvidado))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonLimparPessoas, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonAdicionarPessoas, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1)
                    .addComponent(jComboBoxPessoas, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jButtonLimparItens, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonAdicionarItens, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel4)
                        .addComponent(jLabel2)
                        .addComponent(jComboBoxItens, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)))
                .addGap(45, 45, 45)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jComboBoxItens, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButtonLimparItens, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonAdicionarItens, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxPessoas, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonAdicionarPessoas, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonLimparPessoas, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jMenuCadPessoa.setText("      Cadastrar Pessoa");
        jMenuCadPessoa.setMinimumSize(new java.awt.Dimension(60, 25));
        jMenuCadPessoa.setPreferredSize(new java.awt.Dimension(140, 35));
        jMenuCadPessoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuCadPessoaMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuCadPessoa);

        jMenuCadItens.setText("   Cadastrar Itens");
        jMenuCadItens.setPreferredSize(new java.awt.Dimension(115, 35));
        jMenuCadItens.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuCadItensMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuCadItens);

        jMenuSobre.setText("       Sobre");
        jMenuSobre.setPreferredSize(new java.awt.Dimension(90, 35));
        jMenuSobre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuSobreMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuSobre);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuCadPessoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuCadPessoaMouseClicked
        // TODO add your handling code here:
        CadPessoas cadp = new CadPessoas();
        cadp.setVisible(true);
    }//GEN-LAST:event_jMenuCadPessoaMouseClicked

    private void jMenuCadItensMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuCadItensMouseClicked
        // TODO add your handling code here:
        CadItens cadi = new CadItens();
        cadi.setVisible(true);
    }//GEN-LAST:event_jMenuCadItensMouseClicked

    private void jMenuSobreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuSobreMouseClicked
        // TODO add your handling code here:
        Sobre sob = new Sobre();
        sob.setVisible(true);
    }//GEN-LAST:event_jMenuSobreMouseClicked

    private void jButtonAdicionarPessoasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdicionarPessoasActionPerformed
        // TODO add your handling code here:
        String pessoa = jComboBoxPessoas.getSelectedItem().toString();
        modeloPessoas.addElement(pessoa); 
        jListConvidados.setModel(modeloPessoas);   

        contC++;

        jLabelNumConvidados.setText(Integer.toString(contC));
        jComboBoxPessoas.setSelectedIndex(-1);

        
    }//GEN-LAST:event_jButtonAdicionarPessoasActionPerformed

    private void jButtonAdicionarItensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdicionarItensActionPerformed
        // TODO add your handling code here:
        String item = jComboBoxItens.getSelectedItem().toString();
        modeloItens.addElement(item); 
        jListItens.setModel(modeloItens);
        
        for (int x = 0; x < jListItens.getModel().getSize(); x++) {
            Item it = (Item) listaItem.get(x);
            if (it instanceof Bebida) {
                Bebida bebida = (Bebida) it;
                custoBebidas = custoBebidas + (bebida.getPreco());
                System.out.println("Soma das bebidas: " + custoBebidas);
            } else if (it instanceof Comida) {
                Comida comida = (Comida) it;
                custoComidas = custoComidas + (comida.getPreco());
                System.out.println("Soma das comidas: " + custoComidas);
            }
        }

        jLabelCustoComidas.setText(Float.toString(custoComidas));
        jLabelCustoBebidas.setText(Float.toString(custoBebidas));
        custoTotal = custoBebidas + custoComidas;
        jLabelCustoTotal.setText(Float.toString(custoTotal));
        custoConvidado = (custoTotal/contC);
        jLabelCustoConvidado.setText(Float.toString(custoConvidado));
        jComboBoxItens.setSelectedIndex(-1);
    }//GEN-LAST:event_jButtonAdicionarItensActionPerformed

    private void jButtonLimparPessoasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparPessoasActionPerformed
        // TODO add your handling code here:
        modeloPessoas.clear();
        jListConvidados.setModel(modeloPessoas);
        
        jLabelNumConvidados.setText("XX");
        contC = 0;
        custoConvidado = 0;
     
        jComboBoxPessoas.setSelectedIndex(-1);
    }//GEN-LAST:event_jButtonLimparPessoasActionPerformed

    private void jButtonLimparItensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparItensActionPerformed
        // TODO add your handling code here:
        modeloItens.clear();
        jListItens.setModel(modeloItens);
        
        custoComidas = 0;
        custoBebidas = 0;
        custoTotal = 0;
        jComboBoxItens.setSelectedIndex(-1);
        jLabelCustoComidas.setText("XX");
        jLabelCustoBebidas.setText("XX");
        jLabelCustoTotal.setText("XX");
        jLabelCustoConvidado.setText("XX");
    }//GEN-LAST:event_jButtonLimparItensActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdicionarItens;
    private javax.swing.JButton jButtonAdicionarPessoas;
    private javax.swing.JButton jButtonLimparItens;
    private javax.swing.JButton jButtonLimparPessoas;
    private static javax.swing.JComboBox<String> jComboBoxItens;
    private static javax.swing.JComboBox<String> jComboBoxPessoas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelCustoBebidas;
    private javax.swing.JLabel jLabelCustoComidas;
    private javax.swing.JLabel jLabelCustoConvidado;
    private javax.swing.JLabel jLabelCustoTotal;
    private javax.swing.JLabel jLabelNumConvidados;
    private javax.swing.JList<String> jListConvidados;
    private javax.swing.JList<String> jListItens;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCadItens;
    private javax.swing.JMenu jMenuCadPessoa;
    private javax.swing.JMenu jMenuSobre;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
